lections/flask-template/app/views/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_user, logout_user, current_user
from sqlalchemy import func

from app.models import User
from app.forms import (
    LoginForm,
    RegistrationForm,
    ProfileForm,
    ForgotPasswordForm,
    PasswordResetForm,
)

auth_blueprint = Blueprint("auth", __name__)


@auth_blueprint.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.authenticate(form.user_identifier.data, form.password.data)
        if user:
            login_user(user)
            flash("Login successful.", "success")
            return redirect(url_for("main.index"))
        flash("Wrong username or password.", "danger")
    return render_template("auth/login.html", form=form)


@auth_blueprint.route("/logout", methods=["GET"])
def logout():
    logout_user()
    flash("Logout successful.", "success")
    return redirect(url_for("main.index"))


@auth_blueprint.route("/register", methods=["GET", "POST"])
def register():
    form = RegistrationForm(request.form)
    if form.validate_on_submit():
        user = User(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
        )
        user.save()
        login_user(user)
        flash("Registration successful. You are logged in.", "success")
        return redirect(url_for("main.index"))
    elif form.is_submitted():
        flash("The given data was invalid.", "danger")
    return render_template("auth/register.html", form=form)


@auth_blueprint.route("/profile", methods=["GET", "POST"])
def profile():
    user: User = User.query.get(current_user.id)
    form = ProfileForm()
    if form.validate_on_submit():
        user.first_name = (form.first_name.data,)
        user.last_name = (form.last_name.data,)
        user.username = (form.username.data,)
        user.email = (form.email.data,)
        user.save()

        flash("Profile has been successfully updated", "info")
        return redirect(url_for("main.index"))
    elif form.is_submitted():
        flash("The given data was invalid.", "danger")
    elif request.method == "GET":
        form.first_name.data = user.first_name
        form.last_name.data = user.last_name
        form.username.data = user.username
        form.email.data = user.email
    return render_template("auth/profile.html", form=form)


@auth_blueprint.route("/reset-password", methods=["GET", "POST"])
def reset_password():
    form = ForgotPasswordForm()
    if form.validate_on_submit():
        user: User = User.query.filter(
            func.lower(User.email) == func.lower(form.email.data)
        ).first()
        if user:
            user.reset_password()
            print(
                url_for(
                    "auth.password_reset",
                    reset_password_uuid=user.reset_password_uuid,
                    _external=True,
                )
            )
            flash("Password reset successful.", "success")
            return redirect(url_for("main.index"))
        flash("User not found.", "danger")
    elif form.is_submitted():
        flash("The given data was invalid.", "danger")
    return render_template("auth/reset_password.html", form=form)


@auth_blueprint.route("/password-reset/<reset_password_uuid>", methods=["GET", "POST"])
def password_reset(reset_password_uuid: str):
    user: User = User.query.filter(
        User.reset_password_uuid == reset_password_uuid
    ).first()
    if not user:
        flash("User not found.", "danger")
        return redirect(url_for("main.index"))
    form = PasswordResetForm()
    if form.validate_on_submit():
        user.password = form.password.data
        user.reset_password_uuid = ""
        user.save()
        login_user(user)
        flash("Login successful.", "success")
        return redirect(url_for("main.index"))
    elif form.is_submitted():
        flash("The given data was invalid.", "danger")
    return render_template(
        "auth/password_reset.html", form=form, reset_password_uuid=reset_password_uuid
    )

lections/flask-template/app/views/main.py
from flask import render_template, Blueprint


main_blueprint = Blueprint("main", __name__)


@main_blueprint.route("/")
def index():
    return render_template("index.html")

@main_blueprint.route("/about")
def about():
    return render_template("about.html")

lections/flask-template/app/views/upload.py
from flask import Blueprint, redirect, url_for, flash, render_template
from flask_login import login_required

from app.forms import UploadForm
from app.controllers import upload_recipient_controller

upload_blueprint = Blueprint("upload", __name__)


@upload_blueprint.route("/upload-csv", methods=["GET", "POST"])
@login_required
def file_csv():
    form = UploadForm()
    if form.validate_on_submit():
        upload_recipient_controller(form.file.data)
        flash("Upload success.", "success")
        return redirect(url_for("recipient.list"))
    elif form.is_submitted():
        flash("The given data was invalid.", "danger")
    return render_template("upload/file.html", form=form)

lections/flask-template/app/templates/common/footer.html
<footer class="footer fixed-bottom text-center text-lg-start bg-light text-muted">
  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2022 Copyright: All right reserved!
  </div>
  <!-- Copyright -->
</footer>

lections/flask-template/app/templates/common/header.html
<header>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
    <div class="container">
      <!-- Navbar Brand -->
      <a class="navbar-brand" href="{{ url_for('main.index') }}">{{ config.APP_NAME }}</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <!-- Main Navigation -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('upload.file_csv') }}">Upload CSV</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('recipient.list') }}">Recipients</a>
          </li>
        </ul>
        <!-- Login/Logout -->
        <ul class="navbar-nav ml-auto">
        {% if current_user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="userActions" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">{{current_user.username | capitalize}}</a>
            <div class="dropdown-menu" aria-labelledby="userActions">
              <a class="dropdown-item" href="{{ url_for('auth.profile') }}">Profile</a>
              <a class="dropdown-item" href="{{ url_for('auth.logout') }}">Logout</a>
            </div>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
          </li>
        {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</header>

lections/flask-template/app/templates/common/messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  {% for category, message in messages %}
  <div class="alert alert-{{ category }} alert-dismisible">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span>
    </button>
    {{ message }}
  </div>
  {% endfor %}
  {% endif %}
{% endwith %}